# First and base playbook will ping the node servers
---
- hosts: all #it will pick the all nodes servers
  gather_facts: yes #this will check hardware is working fine
  remote_user: ubuntu #root user that can access node servers
  tasks:
     - name: Test connection
       ping:    #module
       remote_user: ubuntu #run commands by which users you want
...
