- hosts: tag_Name_sonarqubeServers
  become: true
  tasks:    
    - name: Install Java
      apt: name={{ item }} update_cache=yes state=present
      with_items:
          - openjdk-17-jdk
    - name: install unzip
      apt:
        name: unzip
    - name: add sonar
      user:
        name: sonar
        shell: /sbin/nologin
    - name: get_installer
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.3.79811.zip
        dest: /tmp/
    - name: copy
      copy:
        src: /tmp/sonarqube-10.0.0.68432.zip
        dest: /opt/
        remote_src: yes
    - name: install
      shell: sudo unzip /opt/sonarqube-10.0.0.68432.zip
    - name: Change file ownership, group and permissions
      file:
        path: /etc/sonarqube-9.9.3.79811
        owner: sonar
        group: sonar
        recurse: yes
        state: directory
    - name: rename sonar folder
      shell: mv /opt/sonarqube-9.9.3.79811 /etc/sonarqube
    - name: make sonar.service
      file:
        path: /etc/systemd/system/sonar.service
        state:  touch
    - name: edit tomcat.service
      blockinfile:
        dest: /etc/systemd/system/sonar.service
        insertafter:
        block: |
          [Unit]
              Description=SonarQube service
              After=syslog.target network.target
              [Service]
              Type=forking
              ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
              ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
              User=sonar
              Group=sonar
              Restart=always
              LimitNOFILE=65536
              LimitNPROC=4096
              [Install]
              WantedBy=multi-user.target
    - name: chmod 755 sonar.service
      file:
        path: /etc/systemd/system/sonar.service
        mode:  0755
    - name: start sonar
      systemd:
        name: sonar.service
        state: started
        daemon_reload: yes
        enabled: yes
