---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Install wget
    apt:
      name: wget
    become: true

  - name: Install Java
    apt:
      name: openjdk-17-jdk
      update_cache: yes
    become: true

  - name: Add Jenkins key
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present
    become: true

  - name: Add Jenkins repo
    apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: jenkins.list
    become: true

  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
    become: true

  - name: Install fontconfig
    apt:
      name: fontconfig
    become: true

  - name: Install Jenkins
    apt:
      name: jenkins
    become: true
    notify: restart jenkins

  - name: Wait for Jenkins to start
    wait_for:
      delay: 30
      port: 8080

  - name: Get initial admin password for Jenkins
    uri:
      url: http://localhost:8080/login?from=%2F
      return_content: yes
      follow_redirects: all
    register: result
    changed_when: false

  - name: Print initial admin password for Jenkins
    debug:
      msg: "The initial admin password for Jenkins is {{ result.content | regex_search('(?<=<pre>)(.*?)(?=</pre>)') }}"

  handlers:
  - name: restart jenkins
    systemd:
      state: restarted
      name: jenkins
      enabled: yes
    become: true
