---
- hosts: localhost
  gather_facts: false
  become: true
  tasks:
  - name: install wget
    apt:
     name: wget
     state: present
  - name: Install Java
      apt: name={{ item }} update_cache=yes state=present
      with_items:
          - openjdk-17-jdk
          
  - name: download jenkins key
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      dest: /usr/share/keyrings/jenkins-keyring.asc

  - name: Add Jenkins repo
    ansible.builtin.apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: jenkins.list  

  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest

  - name: Install fontconfig
    shell: apt install fontconfig -y 

    - name: Install the Jenkins
    ansible.builtin.apt:
      name: jenkins
      state: present  

  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: jenkins
      enabled: yes

  - name: sleep for 30 seconds and continue with play
    wait_for:
     delay: 30
     port: 8080

  - name: init password jenkin
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result

  - name: print init password jenkins
    debug:
     var: result.stdout
