
#this playbook is used to copy files to node servers
---
- hosts: all #it will pick the all nodes servers
  become: true #it will get root access
  tasks:
      - name: Copy files to nodes
        copy:
          src: /tmp/thop #source destination path
          dest: /home/ubuntu #target destination path
          owner: root #user name
          group: root #group name
          mode: 0666 #file permissions
...

