---
-host: all #it will pick the all nodes servers
 gather_facts: no #this will check hardware working fine
 become: true #it will get root access
 remote_user: ec2-user #root user that can access node servers
 tasks:
     -name: Copy files to nodes
      copy: src = /home/ec2-user/thop #source destination path
            dest = /etc/thop #target destination path
            owner = root #user name
            group = root #group name
            mode = 0666 #file permissions
---
 
